version: '3.3'
services:
  mysqldb:
    build: ./db/MYSQL
    #restart: always
    env_file:
      - ./db/mysql.env
    container_name: db_mysql
    environment:
      - TZ=Asia/Seoul
    ports:
      # 로컬:컨테이너
      - '3333:3306'
    volumes:
      - ./db/MYSQL/res/data/:/var/lib/mysql

  backend_spring:
    build: ./backend
    env_file:
      - ./backend/backend.env
    container_name: backend_spring
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/srv/docker-server
       #&& java -jar /srv/docker-server/build/libs/backend-0.0.1-SNAPSHOT.jar

  backend_signaling_server:
    build: ./backend_chatting
    container_name: backend_signaling_server
    env_file:
      - ./backend_chatting/node.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend_chatting:/srv/docker-server

  front_node:
    build: ./front
    container_name: front_node
    env_file:
      - ./front/front.env
    ports:
      - '3000:3000'
    volumes:
      - ./front:/srv/docker-server

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb/db:/data/db
      - ./db/mongodb/docker-entrypoint-initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    env_file:
      - ./db/mongodb.env

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379